server:
  port: 8380
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/placidenduwayo1/AEPC-Config-Service.git
          default-label: main
  main:
    banner-mode: off
  message: configuration server default profile is working
