server:
  port: 8280
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/placidenduwayo1/AEPC-Config-Service.git
          default-label: main
  main:
    banner-mode: off
  message: configuration server develop profile is working
  application:
    name: ms-config-service
  config:
    activate:
      on-profile: develop

